### ISSUE TITLE
Metrics are broken

### ISSUE THREAD

**Issue by amarao** [lidofinance/depositor-bot#104]
Our old tests checked that metric port is listening. Those tests were green, because of docker-proxy.
New tests started to check if metrics are present and I found that it, actually, is not providing metrics at all (connection refused for port 8080).

**Comment by n0guest** [comment]
It isn't fully broken, it's a half-broken:

1. metrics are [scraped in fact](https://grafana.testnet.fi/explore?orgId=1&left=%7B%22datasource%22:%22Prometheus%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22depositor_bot_account_balance%22,%22range%22:true,%22exemplar%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)
2. defaults of roles and defaults for [prometheus port](https://github.com/lidofinance/depositor-bot/search?q=9000) aren't corellate

In fact, we should fix a role, because for now there is nothing to fix in the app itself.
